spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.142.129:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: 192.168.142.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 192.168.142.129
    port: 6379
